bdsSnmpAdapter:
  loggingLevel: debug
  rotatingLogFile: /tmp/bdsSnmpAdapter_   #FIXME store this at permament location
  asyncioSnmpAgentTest:
    listeningIP: 0.0.0.0  #SNMP get/getNext listening IP address
    listeningPort: 5161 #SNMP get/getNext listening port
    version: 2c # specify snmp version type=str, choices=['2c', '3']
    community: public # v2c community
    usmUserTuples: "engine,user,authkey,privkey"
                  # "80000a4c010a090150,usr-sha-aes128,authkey1,privkey1
                  # one entry per SNMP vยง server
