---
config:
  snmp:
    listeningAddress: 0.0.0.0
    listeningPort: 161    
    version: v2c
    community: public
    oidMappingFile: snmpOidMapping.yml
  bdsAccess:
    confd:
      host: 10.0.3.50
      port: 2002
    bgp-iod:
      host: 10.0.3.50
      port: 3102
    fwdd:
      host: 10.0.3.50
      port: 5002