---
config:
  snmp:
    listeningAddress: 0.0.0.0
    listeningPort: 161    
    version: v2c
    community: public
    oidMappingFile: snmpOidMapping.yml
  bdsAccess:
    confd:
      host: 10.8.3.50
      port: 2002
    bgp-iod:
      host: 10.8.3.50
      port: 2111
    bgp-appd:
      host: 10.8.3.50
      port: 2411